
/*
author: Paul Kim
date: February 22, 2024
version: 1.0
description: layout for CapyNext
 */

import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'CapyNext',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col min-h-screen'>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
